### ISSUE TITLE
Feature request from LXDAO

### ISSUE THREAD

**Issue by zramsay** [cerc-io/mobymask-v2-watcher-ts#4]
Hello Laconic, we've recently encountered some challenges while developing the Report History feature for the mobymask project and are seeking help from the community.

Our requirements are as follows:

1. When a user submits a report, we want to listen to the event to capture and record the reported user information.
- The recorded information should include:
   - The public key address used for signing
   - The public key address of the authorized account for the signature address (usually the owner)
   - The reported information type and value (true or false)
   - The submission time

2. Provide a query interface (GraphQL) that allows:
- Retrieving all submission records based on the signing public key address
- Retrieving all submission records for authorized addresses based on the authorizer's public key address

The challenges we're facing:

We previously attempted to implement this feature within the handleEvent method in the watcher-ts project. We used recoverInvocationSigner to parse the transaction signature, obtaining the submitter's public key address and the authorizing address, and then recorded this information in the database. we have implemented most functions, but not all, because we are not particularly familiar with the overall architecture, and there are certain difficulties in server-side development.

However, as the project structure has been continuously adjusted, the contents of watcher-ts have been dispersed into separate GitHub repositories, making development difficult. In addition, we lack experience in environment setup and deployment and often encounter problems. Therefore, we hope to receive support from the laconic team to help us implement these two features. This way, our front-end development team can use the GraphQL interface to implement the web page functionalities.

Screenshot of the Report History function: 
![Untitled](https://github.com/cerc-io/mobymask-v2-watcher-ts/assets/8304391/fa4a2ddb-9ca4-434f-8699-b0f4551dc626)

**Comment by AFDudley** [comment]
This is a great start, but we need to work with @ashwinphatak to make sure this gets converted into a formalized ask.

**Comment by ashwinphatak** [comment]
It's not exactly clear to me what data is being requested. Best way to communicate this would be to paste example payloads here (e.g. assume Alice, Bob, Charlie invitation chain, with each of them reporting phishers too), and pointing out which fields in the payload (with derivation when required) correspond to which fields in the UI.

**Comment by zramsay** [comment]
Here's the repo and file for reporting history
https://github.com/lxdao-official/mobymask-ui/blob/main/src/views/ReportHistory.jsx
